import type { CourseRecord } from '../types'
import { createAttachmentList } from '../utils/attachments'

const attachments = createAttachmentList

export const initialCourses: CourseRecord[] = [
  {
    id: 'KC-2026-041',
    title: '《出师表》精讲课件',
    series: '松鼠语文',
    subject: '语文',
    educationStage: '初中',
    grade: '九年级',
    volume: '下册',
    textbook: '统编版',
    chapterName: '第六单元',
    orderType: '全新订单',
    isBEnd: '否',
    hasLessonPlan: '有',
    hasScript: '有',
    artCopyright: '否',
    textCopyright: '否',
    version: 'v1.0',
    status: 'pendingStyleDispatch',
    currentOwner: '设计统筹 · 林薇',
    researchDueDate: '2026-04-19',
    finalDueDate: '2026-04-24',
    overallDueDate: '2026-04-24',
    overdue: false,
    researchTeacher: '陈老师',
    researchOwner: '陈老师',
    actualResearchSubmissionDate: '2026-04-19',
    researchSourceFiles: attachments(['《出师表》精讲课件_课件原稿.pptx']),
    lessonPlanFiles: attachments(['《出师表》精讲课件_教案.docx']),
    scriptFiles: attachments(['《出师表》精讲课件_逐字稿.docx']),
    guideFiles: attachments([]),
    otherResearchFiles: attachments(['板书参考图.pdf']),
    researchAttachments: attachments([
      '《出师表》精讲课件_课件原稿.pptx',
      '《出师表》精讲课件_教案.docx',
      '《出师表》精讲课件_逐字稿.docx',
      '板书参考图.pdf',
    ]),
    researchReviewStatus: '审核通过',
    coordinator: '林薇',
    styleDesigners: [],
    styleDueDate: '2026-04-20',
    styleAttachments: attachments([]),
    styleNamingPassed: false,
    pageDesigners: [],
    pageLead: '待派单',
    pageDueDate: '2026-04-24',
    pageAttachments: attachments([]),
    pageNamingPassed: false,
    qualityCheck: '待生成',
    fileCountCheckPassed: false,
    namingCheckPassed: false,
    attachments: attachments(['教研资料包.zip', '板书参考图.pdf']),
    tickets: [],
    logs: [
      {
        id: 1,
        time: '2026-04-18 09:20',
        actor: '计划员 · 赵敏',
        action: '创建任务工单',
        detail: '录入基础信息并设置教研与成品节点',
      },
      {
        id: 2,
        time: '2026-04-19 15:30',
        actor: '教研老师 · 陈老师',
        action: '确认教研完成',
        detail: '上传教研资料包，系统流转至待风格稿派单',
      },
    ],
    stages: [
      {
        key: 'research',
        label: '教研任务',
        ownerRole: '教研老师',
        owner: '陈老师',
        deliverable: '教研资料包',
        dueDate: '2026-04-19',
        state: 'done',
        note: '资料已上传，线下确认完成',
      },
      {
        key: 'style',
        label: '风格稿任务',
        ownerRole: '设计统筹',
        owner: '林薇',
        deliverable: '风格稿派单',
        dueDate: '2026-04-20',
        state: 'active',
      },
      {
        key: 'page',
        label: '内页任务',
        ownerRole: '设计统筹',
        owner: '待派单',
        deliverable: '内页成品',
        dueDate: '2026-04-22',
        state: 'pending',
      },
      {
        key: 'archive',
        label: '入库任务',
        ownerRole: '设计统筹',
        owner: '待确认',
        deliverable: '压缩包与归档记录',
        dueDate: '2026-04-24',
        state: 'pending',
      },
    ],
  },
  {
    id: 'KC-2026-038',
    title: '《二次函数》课堂提升包',
    series: '一起课件',
    subject: '数学',
    educationStage: '初中',
    grade: '九年级',
    volume: '下册',
    textbook: '北师大版',
    chapterName: '第二单元',
    orderType: '全新订单',
    isBEnd: '是',
    hasLessonPlan: '有',
    hasScript: '无',
    artCopyright: '是',
    textCopyright: '是',
    version: 'v1.0',
    status: 'pageInProgress',
    currentOwner: '内页主设计师 · 江栩',
    researchDueDate: '2026-04-16',
    finalDueDate: '2026-04-21',
    overallDueDate: '2026-04-21',
    overdue: true,
    researchTeacher: '徐老师',
    researchOwner: '徐老师',
    actualResearchSubmissionDate: '2026-04-16',
    researchSourceFiles: attachments(['《二次函数》课堂提升包_课件原稿.pptx']),
    lessonPlanFiles: attachments(['《二次函数》课堂提升包_教案.docx']),
    scriptFiles: attachments([]),
    guideFiles: attachments([]),
    otherResearchFiles: attachments([]),
    researchAttachments: attachments([
      '《二次函数》课堂提升包_课件原稿.pptx',
      '《二次函数》课堂提升包_教案.docx',
    ]),
    researchReviewStatus: '审核通过',
    coordinator: '许棠',
    styleDesigners: ['唐婧', '陆鸣'],
    styleDueDate: '2026-04-18',
    styleAttachments: attachments(['《二次函数》课堂提升包_风格稿_v1.0.sketch']),
    styleNamingPassed: true,
    pageDesigners: ['江栩', '余璟'],
    pageLead: '江栩',
    pageAssignments: [
      { designer: '江栩', pageCount: 12 },
      { designer: '余璟', pageCount: 8 },
    ],
    pageDueDate: '2026-04-20',
    pageAttachments: attachments(['《二次函数》课堂提升包_内页成品_v1.0.zip']),
    pageNamingPassed: false,
    qualityCheck: '待生成',
    fileCountCheckPassed: false,
    namingCheckPassed: false,
    attachments: attachments(['教研资料包.zip', '风格稿终版.sketch']),
    tickets: [],
    logs: [
      {
        id: 1,
        time: '2026-04-15 10:10',
        actor: '计划员 · 周舟',
        action: '创建任务工单',
        detail: '课件计划进入主流程',
      },
      {
        id: 2,
        time: '2026-04-17 18:40',
        actor: '设计统筹 · 许棠',
        action: '完成风格稿派单',
        detail: '指派唐婧为主设计师，风格稿截止 4 月 18 日',
      },
      {
        id: 3,
        time: '2026-04-18 20:05',
        actor: '风格稿设计师 · 唐婧',
        action: '上传风格稿',
        detail: '上传即视为线下确认完成，等待内页派单',
      },
      {
        id: 4,
        time: '2026-04-19 09:10',
        actor: '设计统筹 · 许棠',
        action: '完成内页派单',
        detail: '指派江栩、余璟协作，江栩为主设计师',
      },
    ],
    stages: [
      {
        key: 'research',
        label: '教研任务',
        ownerRole: '教研老师',
        owner: '徐老师',
        deliverable: '教研资料包',
        dueDate: '2026-04-16',
        state: 'done',
      },
      {
        key: 'style',
        label: '风格稿任务',
        ownerRole: '风格稿设计师',
        owner: '唐婧',
        deliverable: '风格稿成品',
        dueDate: '2026-04-18',
        state: 'done',
      },
      {
        key: 'page',
        label: '内页任务',
        ownerRole: '内页设计师',
        owner: '江栩 / 余璟',
        deliverable: '内页成品',
        dueDate: '2026-04-20',
        state: 'active',
        note: '当前已逾期，系统自动标红',
      },
      {
        key: 'archive',
        label: '入库任务',
        ownerRole: '设计统筹',
        owner: '许棠',
        deliverable: '完整性报告与入库确认',
        dueDate: '2026-04-21',
        state: 'pending',
      },
    ],
  },
  {
    id: 'KC-2026-027',
    title: '《水循环》探究式课件',
    series: '科学拓展',
    subject: '科学',
    educationStage: '小学',
    grade: '五年级',
    volume: '下册',
    textbook: '通用版',
    chapterName: '第三单元',
    orderType: '全新订单',
    isBEnd: '否',
    hasLessonPlan: '有',
    hasScript: '无',
    artCopyright: '否',
    textCopyright: '否',
    version: 'v1.0',
    status: 'pendingArchive',
    currentOwner: '设计统筹 · 宋澜',
    researchDueDate: '2026-04-17',
    finalDueDate: '2026-04-22',
    overallDueDate: '2026-04-22',
    overdue: false,
    researchTeacher: '叶老师',
    researchOwner: '叶老师',
    actualResearchSubmissionDate: '2026-04-17',
    researchSourceFiles: attachments(['《水循环》探究式课件_课件原稿.pptx']),
    lessonPlanFiles: attachments(['《水循环》探究式课件_教案.docx']),
    scriptFiles: attachments([]),
    guideFiles: attachments(['《水循环》探究式课件_导学案.docx']),
    otherResearchFiles: attachments([]),
    researchAttachments: attachments([
      '《水循环》探究式课件_课件原稿.pptx',
      '《水循环》探究式课件_教案.docx',
      '《水循环》探究式课件_导学案.docx',
    ]),
    researchReviewStatus: '审核通过',
    coordinator: '宋澜',
    styleDesigners: ['陆鸣'],
    styleDueDate: '2026-04-18',
    styleAttachments: attachments(['《水循环》探究式课件_风格稿_v1.0.fig']),
    styleNamingPassed: true,
    pageDesigners: ['闻溪'],
    pageLead: '闻溪',
    pageAssignments: [{ designer: '闻溪', pageCount: 14 }],
    pageDueDate: '2026-04-19',
    pageAttachments: attachments(['《水循环》探究式课件_内页成品_v1.0.zip']),
    pageNamingPassed: true,
    qualityCheck: '校验通过',
    fileCountCheckPassed: true,
    namingCheckPassed: true,
    attachments: attachments(['教研资料包.zip', '风格稿终版.fig', '内页成品.zip']),
    tickets: [],
    logs: [
      {
        id: 1,
        time: '2026-04-19 16:50',
        actor: '内页设计师 · 闻溪',
        action: '上传内页成品',
        detail: '系统校验文件数量与命名规范通过，进入待入库确认',
      },
    ],
    stages: [
      {
        key: 'research',
        label: '教研任务',
        ownerRole: '教研老师',
        owner: '叶老师',
        deliverable: '教研资料包',
        dueDate: '2026-04-17',
        state: 'done',
      },
      {
        key: 'style',
        label: '风格稿任务',
        ownerRole: '风格稿设计师',
        owner: '陆鸣',
        deliverable: '风格稿成品',
        dueDate: '2026-04-18',
        state: 'done',
      },
      {
        key: 'page',
        label: '内页任务',
        ownerRole: '内页设计师',
        owner: '闻溪',
        deliverable: '内页成品',
        dueDate: '2026-04-19',
        state: 'done',
      },
      {
        key: 'archive',
        label: '入库任务',
        ownerRole: '设计统筹',
        owner: '宋澜',
        deliverable: '完整性报告与入库确认',
        dueDate: '2026-04-22',
        state: 'active',
      },
    ],
  },
  {
    id: 'KC-2026-011',
    title: '《古诗词通关》晨读课件',
    series: '晨读计划',
    subject: '语文',
    educationStage: '初中',
    grade: '七年级',
    volume: '上册',
    textbook: '统编版',
    chapterName: '古诗词通关',
    orderType: '全新订单',
    isBEnd: '否',
    hasLessonPlan: '有',
    hasScript: '有',
    artCopyright: '是',
    textCopyright: '是',
    version: 'v2.0',
    status: 'archived',
    currentOwner: '已归档',
    researchDueDate: '2026-04-05',
    finalDueDate: '2026-04-10',
    overallDueDate: '2026-04-10',
    archivedAt: '2026-04-09 19:10',
    overdue: false,
    researchTeacher: '乔老师',
    researchOwner: '乔老师',
    actualResearchSubmissionDate: '2026-04-05',
    researchSourceFiles: attachments(['《古诗词通关》晨读课件_课件原稿.pptx']),
    lessonPlanFiles: attachments(['《古诗词通关》晨读课件_教案.docx']),
    scriptFiles: attachments(['《古诗词通关》晨读课件_逐字稿.docx']),
    guideFiles: attachments([]),
    otherResearchFiles: attachments([]),
    researchAttachments: attachments([
      '《古诗词通关》晨读课件_课件原稿.pptx',
      '《古诗词通关》晨读课件_教案.docx',
      '《古诗词通关》晨读课件_逐字稿.docx',
    ]),
    researchReviewStatus: '审核通过',
    coordinator: '宋澜',
    styleDesigners: ['南音'],
    styleDueDate: '2026-04-06',
    styleAttachments: attachments(['《古诗词通关》晨读课件_风格稿_v2.0.fig']),
    styleNamingPassed: true,
    pageDesigners: ['江栩'],
    pageLead: '江栩',
    pageAssignments: [{ designer: '江栩', pageCount: 18 }],
    pageDueDate: '2026-04-08',
    pageAttachments: attachments(['《古诗词通关》晨读课件_内页成品_v2.0.zip']),
    pageNamingPassed: true,
    qualityCheck: '打包成功',
    fileCountCheckPassed: true,
    namingCheckPassed: true,
    attachments: attachments(['归档压缩包.zip', '完整性报告.pdf']),
    tickets: [
      {
        id: 'SH-1',
        type: '售后',
        responsibility: '设计责任',
        description: '修正一页拼写错误',
        linkedCourseId: 'KC-2026-019',
        requester: '售前 · 高岚',
        createdAt: '2026-04-20 09:15',
        skipStages: [],
        status: '处理中',
        linkedVersion: 'v2.0',
        targetVersion: 'v2.1',
      },
    ],
    logs: [
      {
        id: 1,
        time: '2026-04-09 19:10',
        actor: '系统',
        action: '归档成功',
        detail: '自动打包并写入成品库，课件进入只读状态',
      },
      {
        id: 2,
        time: '2026-04-20 09:15',
        actor: '售前 · 高岚',
        action: '发起售后',
        detail: '反馈晨读页眉拼写错误，计划生成 v2.1',
      },
    ],
    stages: [
      {
        key: 'research',
        label: '教研任务',
        ownerRole: '教研老师',
        owner: '乔老师',
        deliverable: '教研资料包',
        dueDate: '2026-04-05',
        state: 'done',
      },
      {
        key: 'style',
        label: '风格稿任务',
        ownerRole: '风格稿设计师',
        owner: '南音',
        deliverable: '风格稿成品',
        dueDate: '2026-04-06',
        state: 'done',
      },
      {
        key: 'page',
        label: '内页任务',
        ownerRole: '内页设计师',
        owner: '江栩',
        deliverable: '内页成品',
        dueDate: '2026-04-08',
        state: 'done',
      },
      {
        key: 'archive',
        label: '入库任务',
        ownerRole: '系统',
        owner: '自动归档',
        deliverable: '归档压缩包',
        dueDate: '2026-04-09',
        state: 'done',
      },
    ],
  },
  {
    id: 'KC-2026-052',
    title: '《赤壁赋》审美表达课件',
    series: '新业演示',
    subject: '语文',
    educationStage: '高中',
    grade: '高一',
    volume: '必修上',
    textbook: '统编版',
    chapterName: '第三单元',
    orderType: '全新订单',
    isBEnd: '否',
    hasLessonPlan: '有',
    hasScript: '有',
    artCopyright: '是',
    textCopyright: '否',
    version: 'v1.0',
    status: 'research',
    currentOwner: '教研老师 · 赵老师',
    researchDueDate: '2026-04-30',
    finalDueDate: '2026-05-06',
    overallDueDate: '2026-05-06',
    overdue: false,
    researchTeacher: '赵老师',
    researchOwner: '赵老师',
    actualResearchSubmissionDate: undefined,
    researchSourceFiles: attachments([]),
    lessonPlanFiles: attachments([]),
    scriptFiles: attachments([]),
    guideFiles: attachments([]),
    otherResearchFiles: attachments([]),
    researchAttachments: attachments([]),
    researchReviewStatus: '待审核',
    coordinator: '林薇',
    styleDesigners: [],
    styleDueDate: '2026-05-03',
    styleAttachments: attachments([]),
    styleNamingPassed: false,
    pageDesigners: [],
    pageLead: '待派单',
    pageDueDate: '2026-05-06',
    pageAttachments: attachments([]),
    pageNamingPassed: false,
    qualityCheck: '待生成',
    fileCountCheckPassed: false,
    namingCheckPassed: false,
    attachments: attachments([]),
    tickets: [],
    logs: [
      {
        id: 1,
        time: '2026-04-28 09:10',
        actor: '计划员 · 赵敏',
        action: '创建任务工单',
        detail: '已录入制作老师与版权信息，等待教研资料提交',
      },
    ],
    stages: [
      {
        key: 'research',
        label: '教研任务',
        ownerRole: '教研老师',
        owner: '赵老师',
        deliverable: '教研资料包',
        dueDate: '2026-04-30',
        state: 'active',
      },
      {
        key: 'style',
        label: '风格稿任务',
        ownerRole: '设计统筹',
        owner: '待派单',
        deliverable: '风格稿成品',
        dueDate: '2026-05-03',
        state: 'pending',
      },
      {
        key: 'page',
        label: '内页任务',
        ownerRole: '设计统筹',
        owner: '待派单',
        deliverable: '内页成品',
        dueDate: '2026-05-05',
        state: 'pending',
      },
      {
        key: 'archive',
        label: '入库任务',
        ownerRole: '设计统筹',
        owner: '待确认',
        deliverable: '归档压缩包',
        dueDate: '2026-05-06',
        state: 'pending',
      },
    ],
  },
  {
    id: 'KC-2026-053',
    title: '《血压监测规范》医护培训PPT',
    series: '医护PPT',
    subject: '生物',
    educationStage: '高中',
    grade: '高二',
    volume: '选择性必修上',
    textbook: '通用版',
    chapterName: '临床护理规范',
    orderType: '全新订单',
    isBEnd: '是',
    hasLessonPlan: '无',
    hasScript: '有',
    artCopyright: '否',
    textCopyright: '是',
    version: 'v1.0',
    status: 'styleInProgress',
    currentOwner: '风格稿设计师 · 唐婧',
    researchDueDate: '2026-04-25',
    finalDueDate: '2026-05-02',
    overallDueDate: '2026-05-02',
    overdue: false,
    researchTeacher: '韩老师',
    researchOwner: '韩老师',
    actualResearchSubmissionDate: '2026-04-25',
    researchSourceFiles: attachments(['《血压监测规范》医护培训PPT_课件原稿.pptx']),
    lessonPlanFiles: attachments([]),
    scriptFiles: attachments(['《血压监测规范》医护培训PPT_逐字稿.docx']),
    guideFiles: attachments([]),
    otherResearchFiles: attachments(['监测流程参考图.png']),
    researchAttachments: attachments([
      '《血压监测规范》医护培训PPT_课件原稿.pptx',
      '《血压监测规范》医护培训PPT_逐字稿.docx',
      '监测流程参考图.png',
    ]),
    researchReviewStatus: '审核通过',
    coordinator: '许棠',
    styleDesigners: ['唐婧', '陆鸣'],
    styleDueDate: '2026-04-29',
    styleAttachments: attachments([]),
    styleNamingPassed: false,
    pageDesigners: [],
    pageLead: '待派单',
    pageDueDate: '2026-05-02',
    pageAttachments: attachments([]),
    pageNamingPassed: false,
    qualityCheck: '待生成',
    fileCountCheckPassed: false,
    namingCheckPassed: false,
    attachments: attachments(['《血压监测规范》医护培训PPT_课件原稿.pptx', '监测流程参考图.png']),
    tickets: [],
    logs: [
      {
        id: 1,
        time: '2026-04-25 17:20',
        actor: '教研老师 · 韩老师',
        action: '确认教研完成',
        detail: '上传医护培训资料，进入风格稿制作阶段',
      },
      {
        id: 2,
        time: '2026-04-26 10:15',
        actor: '设计统筹 · 许棠',
        action: '完成风格稿派单',
        detail: '指派唐婧主导风格稿制作，陆鸣协作',
      },
    ],
    stages: [
      {
        key: 'research',
        label: '教研任务',
        ownerRole: '教研老师',
        owner: '韩老师',
        deliverable: '教研资料包',
        dueDate: '2026-04-25',
        state: 'done',
      },
      {
        key: 'style',
        label: '风格稿任务',
        ownerRole: '风格稿设计师',
        owner: '唐婧 / 陆鸣',
        deliverable: '风格稿成品',
        dueDate: '2026-04-29',
        state: 'active',
      },
      {
        key: 'page',
        label: '内页任务',
        ownerRole: '设计统筹',
        owner: '待派单',
        deliverable: '内页成品',
        dueDate: '2026-05-01',
        state: 'pending',
      },
      {
        key: 'archive',
        label: '入库任务',
        ownerRole: '设计统筹',
        owner: '待确认',
        deliverable: '归档压缩包',
        dueDate: '2026-05-02',
        state: 'pending',
      },
    ],
  },
  {
    id: 'KC-2026-054',
    title: '《函数图像错题诊断》售后修订单',
    series: '一起课件',
    subject: '数学',
    educationStage: '初中',
    grade: '八年级',
    volume: '下册',
    textbook: '人教版',
    chapterName: '一次函数复习',
    orderType: '售后订单',
    isBEnd: '是',
    hasLessonPlan: '有',
    hasScript: '无',
    artCopyright: '是',
    textCopyright: '是',
    version: 'v2.3',
    status: 'aftersales',
    currentOwner: '计划员 · 当前用户',
    researchDueDate: '2026-04-12',
    finalDueDate: '2026-04-18',
    overallDueDate: '2026-04-30',
    archivedAt: '2026-04-18 20:10',
    overdue: false,
    researchTeacher: '徐老师',
    researchOwner: '徐老师',
    actualResearchSubmissionDate: '2026-04-12',
    researchSourceFiles: attachments(['《函数图像错题诊断》售后修订单_课件原稿.pptx']),
    lessonPlanFiles: attachments(['《函数图像错题诊断》售后修订单_教案.docx']),
    scriptFiles: attachments([]),
    guideFiles: attachments([]),
    otherResearchFiles: attachments([]),
    researchAttachments: attachments([
      '《函数图像错题诊断》售后修订单_课件原稿.pptx',
      '《函数图像错题诊断》售后修订单_教案.docx',
    ]),
    researchReviewStatus: '审核通过',
    coordinator: '许棠',
    styleDesigners: ['南音'],
    styleDueDate: '2026-04-14',
    styleAttachments: attachments(['《函数图像错题诊断》售后修订单_风格稿_v2.3.fig']),
    styleNamingPassed: true,
    pageDesigners: ['江栩'],
    pageLead: '江栩',
    pageAssignments: [{ designer: '江栩', pageCount: 6 }],
    pageDueDate: '2026-04-17',
    pageAttachments: attachments(['《函数图像错题诊断》售后修订单_内页成品_v2.3.zip']),
    pageNamingPassed: true,
    qualityCheck: '打包成功',
    fileCountCheckPassed: true,
    namingCheckPassed: true,
    attachments: attachments(['归档压缩包_v2.3.zip', '完整性报告_v2.3.pdf']),
    tickets: [
      {
        id: 'SH-2026-008',
        type: '售后',
        responsibility: '内容责任',
        description: '修正错题答案和一页坐标轴标签错误',
        linkedCourseId: 'KC-2026-054',
        requester: '售前 · 高岚',
        createdAt: '2026-04-28 10:20',
        skipStages: [],
        status: '处理中',
        linkedVersion: 'v2.3',
        targetVersion: 'v2.4',
      },
    ],
    logs: [
      {
        id: 1,
        time: '2026-04-28 10:20',
        actor: '售前 · 高岚',
        action: '发起售后',
        detail: '客户反馈两处内容错误，进入售后处理中',
      },
    ],
    stages: [
      {
        key: 'research',
        label: '教研任务',
        ownerRole: '教研老师',
        owner: '徐老师',
        deliverable: '教研资料包',
        dueDate: '2026-04-12',
        state: 'done',
      },
      {
        key: 'style',
        label: '风格稿任务',
        ownerRole: '风格稿设计师',
        owner: '南音',
        deliverable: '风格稿成品',
        dueDate: '2026-04-14',
        state: 'done',
      },
      {
        key: 'page',
        label: '内页任务',
        ownerRole: '内页设计师',
        owner: '江栩',
        deliverable: '内页成品',
        dueDate: '2026-04-17',
        state: 'done',
      },
      {
        key: 'archive',
        label: '入库任务',
        ownerRole: '系统',
        owner: '自动归档',
        deliverable: '归档压缩包',
        dueDate: '2026-04-18',
        state: 'done',
      },
    ],
  },
  {
    id: 'KC-2026-055',
    title: '《药物配伍禁忌》版本迭代单',
    series: '医护PPT',
    subject: '化学',
    educationStage: '高中',
    grade: '高三',
    volume: '选择性必修下',
    textbook: '通用版',
    chapterName: '药理安全专题',
    orderType: '迭代订单',
    isBEnd: '是',
    hasLessonPlan: '无',
    hasScript: '有',
    artCopyright: '否',
    textCopyright: '是',
    version: 'v3.0',
    status: 'iteration',
    currentOwner: '计划员 · 当前用户',
    researchDueDate: '2026-04-10',
    finalDueDate: '2026-04-16',
    overallDueDate: '2026-05-03',
    archivedAt: '2026-04-16 18:30',
    overdue: false,
    researchTeacher: '韩老师',
    researchOwner: '韩老师',
    actualResearchSubmissionDate: '2026-04-10',
    researchSourceFiles: attachments(['《药物配伍禁忌》版本迭代单_课件原稿.pptx']),
    lessonPlanFiles: attachments([]),
    scriptFiles: attachments(['《药物配伍禁忌》版本迭代单_逐字稿.docx']),
    guideFiles: attachments([]),
    otherResearchFiles: attachments(['药物图片素材包.zip']),
    researchAttachments: attachments([
      '《药物配伍禁忌》版本迭代单_课件原稿.pptx',
      '《药物配伍禁忌》版本迭代单_逐字稿.docx',
      '药物图片素材包.zip',
    ]),
    researchReviewStatus: '审核通过',
    coordinator: '宋澜',
    styleDesigners: ['唐婧'],
    styleDueDate: '2026-04-12',
    styleAttachments: attachments(['《药物配伍禁忌》版本迭代单_风格稿_v3.0.fig']),
    styleNamingPassed: true,
    pageDesigners: ['闻溪'],
    pageLead: '闻溪',
    pageAssignments: [{ designer: '闻溪', pageCount: 10 }],
    pageDueDate: '2026-04-15',
    pageAttachments: attachments(['《药物配伍禁忌》版本迭代单_内页成品_v3.0.zip']),
    pageNamingPassed: true,
    qualityCheck: '打包成功',
    fileCountCheckPassed: true,
    namingCheckPassed: true,
    attachments: attachments(['归档压缩包_v3.0.zip', '完整性报告_v3.0.pdf']),
    tickets: [
      {
        id: 'IT-2026-003',
        type: '迭代',
        responsibility: '客户需求变更',
        description: '新增药品配伍案例，两页结构调整并补充动态图示',
        linkedCourseId: 'KC-2026-055',
        requester: '计划员 · 赵敏',
        createdAt: '2026-04-28 11:00',
        skipStages: ['教研'],
        status: '处理中',
        linkedVersion: 'v3.0',
        targetVersion: 'v4.0',
      },
    ],
    logs: [
      {
        id: 1,
        time: '2026-04-28 11:00',
        actor: '计划员 · 赵敏',
        action: '发起迭代',
        detail: '客户新增两页案例内容，跳过教研阶段进入迭代处理',
      },
    ],
    stages: [
      {
        key: 'research',
        label: '教研任务',
        ownerRole: '教研老师',
        owner: '韩老师',
        deliverable: '教研资料包',
        dueDate: '2026-04-10',
        state: 'done',
      },
      {
        key: 'style',
        label: '风格稿任务',
        ownerRole: '风格稿设计师',
        owner: '唐婧',
        deliverable: '风格稿成品',
        dueDate: '2026-04-12',
        state: 'done',
      },
      {
        key: 'page',
        label: '内页任务',
        ownerRole: '内页设计师',
        owner: '闻溪',
        deliverable: '内页成品',
        dueDate: '2026-04-15',
        state: 'done',
      },
      {
        key: 'archive',
        label: '入库任务',
        ownerRole: '系统',
        owner: '自动归档',
        deliverable: '归档压缩包',
        dueDate: '2026-04-16',
        state: 'done',
      },
    ],
  },
  {
    id: 'KC-2026-056',
    title: '《浮力实验》课堂互动包',
    series: '新业演示',
    subject: '物理',
    educationStage: '初中',
    grade: '八年级',
    volume: '下册',
    textbook: '人教版',
    chapterName: '实验探究专题',
    orderType: '全新订单',
    isBEnd: '否',
    hasLessonPlan: '有',
    hasScript: '无',
    artCopyright: '否',
    textCopyright: '否',
    version: 'v1.0',
    status: 'packing',
    currentOwner: '系统自动打包',
    researchDueDate: '2026-04-18',
    finalDueDate: '2026-04-26',
    overallDueDate: '2026-04-26',
    overdue: false,
    researchTeacher: '王老师',
    researchOwner: '王老师',
    actualResearchSubmissionDate: '2026-04-18',
    researchSourceFiles: attachments(['《浮力实验》课堂互动包_课件原稿.pptx']),
    lessonPlanFiles: attachments(['《浮力实验》课堂互动包_教案.docx']),
    scriptFiles: attachments([]),
    guideFiles: attachments(['《浮力实验》课堂互动包_导学案.docx']),
    otherResearchFiles: attachments(['实验器材照片.zip']),
    researchAttachments: attachments([
      '《浮力实验》课堂互动包_课件原稿.pptx',
      '《浮力实验》课堂互动包_教案.docx',
      '《浮力实验》课堂互动包_导学案.docx',
      '实验器材照片.zip',
    ]),
    researchReviewStatus: '审核通过',
    coordinator: '宋澜',
    styleDesigners: ['陆鸣'],
    styleDueDate: '2026-04-20',
    styleAttachments: attachments(['《浮力实验》课堂互动包_风格稿_v1.0.fig']),
    styleNamingPassed: true,
    pageDesigners: ['余璟'],
    pageLead: '余璟',
    pageAssignments: [{ designer: '余璟', pageCount: 16 }],
    pageDueDate: '2026-04-24',
    pageAttachments: attachments(['《浮力实验》课堂互动包_内页成品_v1.0.zip']),
    pageNamingPassed: true,
    qualityCheck: '校验通过',
    fileCountCheckPassed: true,
    namingCheckPassed: true,
    attachments: attachments([
      '《浮力实验》课堂互动包_课件原稿.pptx',
      '《浮力实验》课堂互动包_风格稿_v1.0.fig',
      '《浮力实验》课堂互动包_内页成品_v1.0.zip',
    ]),
    tickets: [],
    logs: [
      {
        id: 1,
        time: '2026-04-27 18:05',
        actor: '设计统筹 · 宋澜',
        action: '确认入库',
        detail: '完整性报告校验通过，系统开始自动打包',
      },
    ],
    stages: [
      {
        key: 'research',
        label: '教研任务',
        ownerRole: '教研老师',
        owner: '王老师',
        deliverable: '教研资料包',
        dueDate: '2026-04-18',
        state: 'done',
      },
      {
        key: 'style',
        label: '风格稿任务',
        ownerRole: '风格稿设计师',
        owner: '陆鸣',
        deliverable: '风格稿成品',
        dueDate: '2026-04-20',
        state: 'done',
      },
      {
        key: 'page',
        label: '内页任务',
        ownerRole: '内页设计师',
        owner: '余璟',
        deliverable: '内页成品',
        dueDate: '2026-04-24',
        state: 'done',
      },
      {
        key: 'archive',
        label: '入库任务',
        ownerRole: '系统',
        owner: '自动打包中',
        deliverable: '归档压缩包',
        dueDate: '2026-04-26',
        state: 'active',
      },
    ],
  },
]
